# Generated by Django 5.2.3 on 2025-06-27 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(help_text="e.g., 'Credit Card', 'Bank Transfer', 'PayPal'", max_length=255)),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='Automatically set to the date and time of payment creation')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of the payment', max_digits=10)),
                ('status', models.CharField(help_text="e.g., 'Pending', 'Approved', 'Rejected', 'Completed'", max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, help_text='Automatically set to the date and time of transaction creation')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of this specific transaction', max_digits=10)),
                ('status', models.CharField(help_text="e.g., 'Initiated', 'Processed', 'Failed', 'Refunded'", max_length=255)),
                ('payment', models.ForeignKey(help_text='The payment this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
