# Generated by Django 5.2.3 on 2025-07-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paystack_authorization_url',
            field=models.URLField(blank=True, help_text="URL for the user to complete payment on Paystack's gateway.", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paystack_reference',
            field=models.CharField(blank=True, help_text='Paystack transaction reference ID for this payment.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paystack_charge_id',
            field=models.CharField(blank=True, help_text='Paystack Transaction ID associated with this transaction.', max_length=255, null=True),
        ),
    ]
